### ISSUE TITLE
Cleanup of packages used for building git

### ISSUE THREAD

**Issue by bkraul** [nullbyte91/simple-Sh-DataScience#2]
Thank you so much for your nifty git build script. I am trying to use it in one of my docker builds (for an older version of ubuntu that has the gnutls problem). However, the sideffect is that I end up with a really large image (2.6GB).

Is there anyway the script could be modified to do some cleanup of all build packages that are not necessary after building git? I have tried some cleanup, but I'd figure there could be some more.

**Comment by nullbyte91** [comment]
Thanks for reporting it. I will push the changes in some time.
